### ISSUE TITLE
Display Daily Game Limit and STARK Balance in Header

### ISSUE THREAD

**Issue by Cheelax** [z-korp/zkube#19]
Description:
We need to update the Header component to display the player's daily game limit and ETH balance, and modify the Start button to show the associated cost for starting a game.

Tasks:

1. Update Player Model
    - Add dailyGamesPlayed, dailyGamesLimit with hardcoded values
2. Modify Header Component
    - Add a new section to display "Free Games: X/Y"
    - Show the player's Stark balance
    - Ensure responsive design for both mobile and desktop views
4. Update usePlayer Hook
    - Ensure it fetches the new player properties
    - Add any necessary error handling for new properties
5. Testing
    - Test with various scenarios (free games available, no free games)
    - Verify correct display on different screen sizes

Acceptance Criteria:

- Header displays accurate daily game limit and Starks balance
- UI is responsive and displays correctly on all device sizes
- Players can easily understand their game limit and Starks balance

**Comment by kateberryd** [comment]
Hi

**Comment by Jemiiah** [comment]
I

**Comment by GoSTEAN** [comment]
@Cheelax Can I work on this?

**Comment by martinvibes** [comment]
hello  @Cheelax i would love to work on this if i'm giving the opportuinity to

**Comment by ikemHood** [comment]
I am applying to this issue via [OnlyDust platform](https://app.onlydust.com/p/zkube).

### My background and how it can be leveraged
Hey, I am ikem Peter. a fullstack software developer with 3+ years of working experience, I would love to help out with this issue...

**Comment by PoulavBhowmick03** [comment]
I am applying to this issue via [OnlyDust platform](https://app.onlydust.com/p/zkube).

### My background and how it can be leveraged
I'm Poulav Bhowmick, a software engineer at Invisible Studios with a robust background in TypeScript, Rust, Solidity Cairo, fullstack development and blockchain technology. My experience includes building robust applications, optimizing functionalities and blockchain integration. I have actively participated in events and open source contributions, enhancing my capability to tackle real-world tech challenges. My projects can be viewed on my GitHub Profile and OnlyDust Profile. Plus I´m active member of Starknet community🇷.

### How I plan on tackling this issue
## 1. Update Player Model

First, I'll modify the Player model to include the new properties:

```typescript
interface Player {
  // ... existing properties
  dailyGamesPlayed: number;
  dailyGamesLimit: number;
  starkBalance: number;
}
```

For now, I'll use hardcoded values:

```typescript
const defaultPlayer: Player = {
  // ... existing properties
  dailyGamesPlayed: 0,
  dailyGamesLimit: 5,
  starkBalance: 1000
};
```

## 2. Modify Header Component

Next, I'll update the Header component to display the new information:

```tsx
import React from 'react';
import { usePlayer } from '../hooks/usePlayer';

const Header: React.FC = () => {
  const { player } = usePlayer();

  return (
    <header className="flex justify-between items-center p-4 bg-gray-800 text-white">
      <h1 className="text-2xl font-bold">Ludo Game</h1>
      <div className="flex items-center space-x-4">
        <span className="text-sm">
          Free Games: {player.dailyGamesLimit - player.dailyGamesPlayed}/{player.dailyGamesLimit}
        </span>
        <span className="text-sm">
          Balance: {player.starkBalance} STARK
        </span>
      </div>
    </header>
  );
};

export default Header;
```

## 3. Update usePlayer Hook

I'll modify the usePlayer hook to include the new properties:

```typescript
import { useState, useEffect } from 'react';
import { Player } from '../types/Player';

export const usePlayer = () => {
  const [player, setPlayer] = useState<Player | null>(null);
  const [loading, setLoading] = useState(true);
  const [error, setError] = useState<string | null>(null);

  useEffect(() => {
    const fetchPlayer = async () => {
      try {
        // Simulating API call
        const response = await fetch('/api/player');
        if (!response.ok) {
          throw new Error('Failed to fetch player data');
        }
        const data = await response.json();
        setPlayer(data);
      } catch (err) {
        setError('Error fetching player data');
      } finally {
        setLoading(false);
      }
    };

    fetchPlayer();
  }, []);

  return { player, loading, error };
};
```

## 4. Testing

To test these changes:

1. Create mock data with various scenarios (free games available, no free games).
2. Use React Testing Library to write unit tests for the Header component.
3. Implement end-to-end tests using Cypress to verify the UI across different screen sizes.

Example test for Header component:

```typescript
import React from 'react';
import { render, screen } from '@testing-library/react';
import Header from './Header';
import { PlayerProvider } from '../contexts/PlayerContext';

describe('Header', () => {
  it('displays correct game limit and balance', () => {
    const mockPlayer = {
      dailyGamesPlayed: 2,
      dailyGamesLimit: 5,
      starkBalance: 1000
    };

    render(
      <PlayerProvider value={{ player: mockPlayer }}>
        <Header />
      </PlayerProvider>
    );

    expect(screen.getByText('Free Games: 3/5')).toBeInTheDocument();
    expect(screen.getByText('Balance: 1000 STARK')).toBeInTheDocument();
  });
});
```

## Next Steps
1. Implement the actual API integration for fetching player data.
2. Add error handling and loading states in the UI.
3. Implement the logic for updating the Start button cost based on free games availability.
4. Conduct thorough testing across various devices and screen sizes.

**Comment by Benjtalkshow** [comment]
I am applying to this issue via [OnlyDust platform](https://app.onlydust.com/p/zkube).

### My background and how it can be leveraged
Hi @Cheelax

I’m ready to work on the "Update Header Component" issue. My name is Benjamin, and I have extensive experience in enhancing UI components and integrating dynamic data. My expertise includes building responsive and user-friendly interfaces, with a focus on improving the overall user experience.

### Understanding the Issue
The Header component needs to be updated to display the player's daily game limit and ETH balance, and to modify the Start button to show the associated cost for starting a game. This update will provide players with clear information about their game limits and financial status.


### How I plan on tackling this issue
#### Update Player Model
- **Daily Game Limit**: I will add `dailyGamesPlayed` and `dailyGamesLimit` properties with hardcoded values for initial testing.

#### Modify Header Component
- **New Section**: I will add a section to the Header component to display "Free Games: X/Y" to show the player's remaining daily games.
- **Balance Display**: The player's Stark balance will be displayed in the Header.
- **Responsive Design**: I will ensure the new design is responsive and works well on both mobile and desktop views.

#### Update usePlayer Hook
- **Fetch New Properties**: I will update the `usePlayer` hook to fetch the new properties (`dailyGamesPlayed`, `dailyGamesLimit`, and Stark balance).
- **Error Handling**: I will add necessary error handling to manage any issues related to fetching these new properties.

#### Testing
- **Various Scenarios**: I will test the Header component with different scenarios, including cases where free games are available and where there are no free games left.
- **Screen Sizes**: I will verify that the Header component displays correctly on different screen sizes.

**Comment by BrightDU** [comment]
I am applying to this issue via [OnlyDust platform](https://app.onlydust.com/p/zkube).

### My background and how it can be leveraged
My name is Bright. I am a full-stack developer with over 7 years of experience building enterprise applications. I am a team player, and I enjoy collaborative problem-solving.

### How I plan on tackling this issue
I will update the player model, header component, usePlayer hook, and test the UI. I will introduce two new fields to track daily activity and add a section for "Free Games: X/Y" with the player's ETH balance. The usePlayer hook will fetch player properties and error handling will be implemented.

I will test with various scenarios to ensure a seamless user experience.

**Comment by josephchimebuka** [comment]
I am applying to this issue via [OnlyDust platform](https://app.onlydust.com/p/zkube).

### My background and how it can be leveraged
Hello @Cheelax I am Joseph Chimebuka I'm a full-stack software developer with 4+ years of experience in crafting innovative products. I've built a range of projects, including https://mattedsgn.vercel.app/ and https://metacrypt.vercel.app/ showcasing my expertise in React, Next.js, and blockchain technologies. I'm also an active contributor onlydust. here's my account https://app.onlydust.com/u/josephchimebuka.

### How I plan on tackling this issue
I will make sure the criteria's required for  are achieved and while displaying the daily game Limit and STARK Balance in Header

**Comment by Cheelax** [comment]
Hi everyone.
There is a new process for the ODHack, now you must apply to the tasks directly from Onlydust: https://app.onlydust.com/hackathons/odhack-70
We will only look at application made via this process.

**Comment by ikemHood** [comment]
Hey @Cheelax having a little challenge view the UI in developement.
`npm run dev` starts the vite server but accessing it on browser returns 'empty response' what could i have been missing?

**Comment by Cheelax** [comment]
Hey @ikemHood.
First, have you created the .env I provided in the telegram?
If yes, you could try using pnpm

**Comment by ikemHood** [comment]
Ooh, can you please share me a link to the telegram

**Comment by Cheelax** [comment]
https://t.me/+WxczQ7pyEJAyODg0
